![alt text](https://ehhsmath.files.wordpress.com/2013/06/algebra_wordle.png)

# Linear Algebra 

Linear algebra is the branch of mathematics which deals with straight lines, vectors, matrices, multi-dimensional arrays (constructed using linear structures like straight lines or linear planes etc.) and the linear relationships or mappings among these constructs. A set of points or co-ordinates which satisfy a linear equation consitute a 'hyperplane' in an n-dimensional space. The intersection of two hyperplanes is a straight line and the intersections of multiple hyperplanes is a single point, generally regarded as the 'origin'

## Scalars, Vectors, Matrices and Tensors


A single number (generally rational number) is called a 'scalar'. A single point in space can be represented by a set of co-ordinates or scalars, and this is called a 'vector'. In programming parlance, a vector is an array of numbers (scalars). A Matrix is a 2-dimensional array of numbers, or a collection of vectors. A 'tensor' is a multi-dimensional array

![alt text](https://s3.amazonaws.com/refactored/images/ML/images/svmt_new.png)

A 'scalar' can be a numeric variable, an numpy array with numbers is a 'vector'. Similarly, a two-dimensional array can be a matrix and a multi-dimensional array is a 'tensor'. A tensor is generally defined as a geometric object which could represent the linear relationship between scalars, vectors or other tensors (Source: Wikipedia)

# Matrix Operations - Addition, Subtraction, Multiplication, Transpose and Inverse

In [8]:
import numpy as np
A = np.matrix([[1,2,3],
               [4, 7, 19],
               [6,7,8]])
B = np.matrix([[-3,4,-5],
               [4, 4, 5],
               [3,-4,6]])
print(A)
print(B)

[[ 1  2  3]
 [ 4  7 19]
 [ 6  7  8]]
[[-3  4 -5]
 [ 4  4  5]
 [ 3 -4  6]]


### Addition

In [10]:
#A+B
addition=A+B
addition

matrix([[-2,  6, -2],
        [ 8, 11, 24],
        [ 9,  3, 14]])

### Subtraction

In [11]:
#A-B
subtraction=A-B
subtraction

matrix([[ 4, -2,  8],
        [ 0,  3, 14],
        [ 3, 11,  2]])

### Multiplication

![alt text](https://s3.amazonaws.com/refactored/images/ML/images/matmul.png)

In [12]:
#A*B
multiplication=A*B
multiplication

matrix([[ 14,   0,  23],
        [ 73, -32, 129],
        [ 34,  20,  53]])

In [13]:
#5*A
multiply=5*A
multiply

matrix([[ 5, 10, 15],
        [20, 35, 95],
        [30, 35, 40]])

## Transpose of a matrix(np.transpose(x))

A transpose of a matrix is another matrix which results from transforming all the rows of elements of the original matrix into columns. If the order or shape of the matrix is  (i,j)(i,j)  then the transpose of this matrix will have a shape of  (j,i)(j,i) 

![alt text](https://s3.amazonaws.com/refactored/images/ML/images/mattran.png)

In [15]:
#transpose of a is:-
AT=np.transpose(A)
AT

matrix([[ 1,  4,  6],
        [ 2,  7,  7],
        [ 3, 19,  8]])

# Inverse of a matrix(numpy.linalg.inv())

![alt text](https://www.onlinemathlearning.com/image-files/xinverse-matrix.png.pagespeed.ic.o8g8MXJQ0U.webp)

The Inverse of a matrix is the matrix which when multiplied with the original matrix, results in a Identity matrix.

A * A-1 = I

The Inverse of a matrix can be determined by using the 'inv' function of 'linalg' sub-module of numpy ( numpy.linalg.inv() ). This function can be performed on a numpy array (matrix).

![alt text](http://images.slideplayer.com/32/9800716/slides/slide_22.jpg)

In [18]:
Ainverse=np.linalg.inv(A)
Ainverse

matrix([[-1.71111111,  0.11111111,  0.37777778],
        [ 1.82222222, -0.22222222, -0.15555556],
        [-0.31111111,  0.11111111, -0.02222222]])

# Vector Operations - Dot Product and Cross Product

# Dot product(np.dot())

In [20]:
dot=np.dot(A,B)
dot

matrix([[ 14,   0,  23],
        [ 73, -32, 129],
        [ 34,  20,  53]])

![alt text](http://images.slideplayer.com/16/5003517/slides/slide_4.jpg)

# cross product(np1.cross())

In [24]:
cross=np.cross(A,B)
cross

array([[-22,  -4,  10],
       [-41,  56, -12],
       [ 74, -12, -45]])

![alt text](http://www.tigerquesttech.com/Mathematics/Calculus/gifs/cross_product.gif)

## Norm of a vector(numpy.linalg.norm())

The norm of a vector is a numeric value which represents the lenght or size of the vector

Norm of a vector can be calculated using the method numpy.linalg.norm(). The function takes at least two arguments, i.e., the vector (numpy array) and the order of the norm. The default value for order of norm is 2. So when no 'order' argument is specified, the function calculates the second order norm by default.

In [27]:
normA=np.linalg.norm(A,2)
normA

23.778491338535947

![alt text](http://slideplayer.com/slide/5302179/17/images/2/Vector+Norms+Measure+the+magnitude+of+a+vector.jpg)

# Angle between two vectors 

Calculating the angle between two vectors is not a straight forward process in Python The following steps can be followed in order to find out the angle between any two vectors.


1-Normalize the given vectors: Normalizing is the process of converting the length of a vector to '1' while preserving the direction of the vector. This can be done by dividing the vector with its second order norm.


2-Dot product of Normalized vectors: Find out the dot product of the normalized vectors from above step using the numpy.dot function.



3-Clipping the value of the dot product: As we are trying to calculate the angle between vectors using the law of cosines, we should note that the cosine function has a maximum value of '1' and minimum value of '-1'. The dot product calculated in previous step cannot have a value beyond these bounds. Hence we use the 'numpy.clip()' function to limit the result of the dot product. If the value of the dot product of the normalized vectors falls within -1 and 1, it retains its value. If it is less than -1 it assumes a value of -1 and if greater than 1, then it assumes a value of 1.


4-Calculating angle using cos-1 function: We have a value between -1 and 1 which we need to use to calculate the possible angle using the inverse cosine function. This can be acheived using the 'numpy.arccos()' function. Note that the arccos() function returns the angle in radians. In order to convert this result into degrees, the 'numpy.degrees()' function can be used.

![alt text](http://ask.learncbse.in/uploads/db3785/original/2X/f/f91bfb0458f58948852e5045523f0569a8e54d07.png)

### Example for angle between two vectors

In [30]:
v_one = np.array([1,2,1])
v_two = np.array([3,4,5])

v_one_norm = np.linalg.norm(v_one,2)
v_two_norm = np.linalg.norm(v_two,2)
print(v_one_norm,v_two_norm)

v_one_normvec = v_one/v_one_norm
v_two_normvec = v_two/v_two_norm
print(v_one_normvec,v_two_normvec)

v_angle = np.degrees(np.arccos(np.clip(np.dot(v_one_normvec,v_two_normvec),-1.0,1.0)))
print(v_angle)

2.449489742783178 7.0710678118654755
[0.40824829 0.81649658 0.40824829] [0.42426407 0.56568542 0.70710678]
22.51782535822713


# Eigen Values and Eigen Vectors

### What are eigenvectors?


-A Matrix is a mathematical object that acts on a (column) vector, resulting in a new vector, i.e. Ax=b

-An eigenvector is the resulting vector that is parallel to x (some multiple of x)

$$ {A}\underline{x}=\lambda \underline{x} $$

-The eigenvectors with an eigenvalue of zero are the vectors in the nullspace

-If A is singular (takes some non-zero vector into 0) then λ=0

A·v = λ·v

In this equation A is an n-by-n matrix, v is a non-zero n-by-1 vector and λ is a scalar (which may be either real or complex). Any value of λ for which this equation has a solution is known as an eigenvalue of the matrix A. It is sometimes also called the characteristic value. The vector, v, which corresponds to this value is called an eigenvector. The eigenvalue problem can be rewritten as:

(A·v) - (λ·v) = 0 
(A·v) - (λ·I·v) = 0 
(A - (λ·I))·v = 0 
If v is non-zero, this equation will only have a solution if

|A - (λ·I)| = 0

This equation is called the characteristic equation of A, and is an nth order polynomial in λ with n roots.

|A - (λ·I)| = (λ1-λ)(λ2-λ)…(λn-λ) 

### Example of eigenvector and eigenvalue

In [36]:
A

matrix([[ 1,  2,  3],
        [ 4,  7, 19],
        [ 6,  7,  8]])

In [42]:
from scipy import linalg as LA
import numpy as np
Value,Vector=LA.eig(A)


In [43]:
Value#eigen value

array([20.4178883 +0.j, -0.57325332+0.j, -3.84463498+0.j])

In [41]:
Vector#eigen vector

array([[-0.1687588 , -0.64062199,  0.05956476],
       [-0.82152007,  0.75011183, -0.87229433],
       [-0.54463312, -0.164121  ,  0.48533971]])

## Trace of a matrix

In linear algebra, the trace of an n-by-n square matrix A is defined to be the sum of the elements on the main diagonal (the diagonal from the upper left to the lower right) of A

In [47]:
A

matrix([[ 1,  2,  3],
        [ 4,  7, 19],
        [ 6,  7,  8]])

In [49]:
Trace=A.trace()
Trace

matrix([[16]])

## Determinant of a matrix

In Linear Algebra, determinant of a matrix is a special number that can be calculated from a square matrix.



Determinant of a matrix can also be found by product of its eigenvalues

In [50]:
A

matrix([[ 1,  2,  3],
        [ 4,  7, 19],
        [ 6,  7,  8]])

In [52]:
det=np.linalg.det(A)
det

45.000000000000014

## Rank of a matrix

The rank of a matrix is defined as (a) the maximum number of linearly independent column vectors in the matrix or (b) the maximum number of linearly independent row vectors in the matri

The maximum number of linearly independent vectors in a matrix is equal to the number of non-zero rows in its row echelon matrix. Therefore, to find the rank of a matrix, we simply transform the matrix to its row echelon form and count the number of non-zero rows.

In [54]:
A

matrix([[ 1,  2,  3],
        [ 4,  7, 19],
        [ 6,  7,  8]])

In [55]:
rank=np.linalg.matrix_rank(A)
rank

3