![Alt Text](https://www.safaribooksonline.com/library/view/elegant-scipy/9781491922927/assets/elsp_0105.png)

# Array Shape Flattening 

For flattening, ravel() function is used. This function returns a flattened one-dimensional array. A copy is made only if needed. The returned array will have the same type as that of the input array

In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
#array flattening
np.ravel(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Resizing 

Sometimes it required to shrink or expand the current array, this is called resizing. Resizing of an array can be changed with nparray.resize()



In [16]:
b=np.arange(0,5)
b

array([0, 1, 2, 3, 4])

In [19]:
b=np.arange(0,5)
b.resize(9)
b

array([0, 1, 2, 3, 4, 0, 0, 0, 0])

In [14]:
b=np.arange(0,5)
b.resize((3,3))
b


array([[0, 1, 2],
       [3, 4, 0],
       [0, 0, 0]])

## Adding new dimension 

Indexing with the np.newaxis object allows us to add an axis to an array. Simply put, the newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus,

1D array will become 2D array

2D array will become 3D array

3D array will become 4D array and so on..

In [48]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [49]:
a[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5]])

## Transpose of an array 

In [53]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
a.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [59]:
a.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [64]:
#swapping axis
a.swapaxes(1,1)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Array processing 

In [65]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
#Saving array on disk in binary format (file extension .npy)
np.save('my_array',a)

In [69]:
#loading the saved copy
np.load('my_array.npy')

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
b

array([1, 2, 3])

In [71]:
#Saving multiple arrays into a zip file
np.savez('two_arrays.npz',x=a,y=b)

In [75]:
#loading the saved two_array copy
np.load('two_arrays.npz')['y']

array([1, 2, 3])

In [77]:
#Now saving and loading text files

arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('my_test_text.txt',arr,delimiter=',')
arr = np.loadtxt('my_test_text.txt',delimiter = ',')
arr

array([[1., 2., 3.],
       [4., 5., 6.]])