![Alt Text](https://cdn-images-1.medium.com/max/1600/1*mc5YIn7jvo5uwuqBOUDw7Q.jpeg)

# NUMPY

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks

https://docs.scipy.org/doc/numpy-1.10.1/user/install.html

In [118]:
import numpy as np

# Numpy-arrays 

 Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column)

In [119]:
#creating numpy from pythonlist
list=[1,2,3,4]
np.array(list)

array([1, 2, 3, 4])

using np.array we will convert a python list to a numpy array

In [120]:
#example
matrix=[[1,2,3],[4,5,6],[8,9,10]]
np_array=np.array(matrix)
np_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

to know the type and shape of numpy arrays use dtype and shape

In [121]:
np_array.shape

(3, 3)

In [122]:
np_array.dtype

dtype('int32')

### creating numpy arrays with built-in numpy functions

creating array of zeros with zeros()

In [123]:
np.zeros(3)

array([0., 0., 0.])

In [124]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

creating array of ones with ones()

In [125]:
np.ones(3)

array([1., 1., 1.])

In [126]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [127]:
np.empty([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

creating identity matrix with eye()

In [128]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [129]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

### Arange 

Arange Return evenly spaced values within a given interval.

In [130]:
np.arange(0,16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [131]:
#here 2 is the step size 
np.arange(0,16,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

### linspace

linspace Return evenly spaced numbers over a specified interval.

In [132]:
np.linspace(0,50,5) #here 5 is the number of evenly spaced elements

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [133]:
np.linspace(0,50,6) #here 6 is the number of evenly spaced elements

array([ 0., 10., 20., 30., 40., 50.])

### rand

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [134]:
np.random.rand(3) #here 3 is the number of random numbers 

array([0.82777066, 0.88385922, 0.64518857])

In [135]:
np.random.rand(3,3)

array([[0.39384255, 0.10314741, 0.50405173],
       [0.24975405, 0.04044354, 0.73789271],
       [0.49850336, 0.75614662, 0.09004134]])

### randn 

randn return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [136]:
np.random.randn(4) #here 4 is the number of random numbers

array([-0.29570054, -0.30017677,  1.06530296,  1.40923452])

In [137]:
np.random.randn(4,4)

array([[-0.27418909,  0.22661302,  0.81973874, -0.32273018],
       [-1.30801378, -0.07789251, -0.33924628, -0.88073354],
       [-2.16232244, -1.02740529,  0.84973843, -1.05214534],
       [ 0.7067912 ,  1.62207168, -0.47600564, -1.02965781]])

### randint 

randint Return random integers from `low` (inclusive) to `high` (exclusive). 

In [138]:
np.random.randint(1,50,4) #here 1,50 are the lowest & highest values and 4 is the no of random numbers 

array([42, 43, 25, 36])

In [139]:
np.random.randint(1,50,10)

array([11, 12, 27, 39, 38, 13, 16, 21, 13,  4])

In [140]:
np.random.randint(1,50,(3,3))

array([[ 1, 15, 11],
       [19, 26, 46],
       [48, 27, 37]])

## Array functions 

https://docs.scipy.org/doc/numpy/reference/ufuncs.html

In [141]:
#squareroot
a=np.arange(1,10)
a=a.reshape(3,3)
np.sqrt(a)


array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [142]:
#exponential
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [143]:
#log
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

### max,min,argmax,argmin,shape,reshape


In [144]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [145]:
#shape
a.shape

(9,)

In [146]:
#converting array a to (3,3) array with reshape
a=a.reshape(3,3)

In [147]:
#max
a.max()

9

In [148]:
#min
a.min()

1

In [149]:
#argmax is the index of the max value
a.argmax()


8

In [150]:
#argmin is the index of the min value
a.argmin()

0

In [151]:
a.shape

(3, 3)

## Array scalar Arthemetic operations 

In [152]:
a=np.arange(1,10)
array1=a.reshape(3,3)
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [153]:
a=np.arange(11,20)
array2=a.reshape(3,3)
array2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [154]:
#addition
array1+array2

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [155]:
#subtraction
array1-array2

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [156]:
#multiplication
array1 * array2

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [157]:
#division
array1/array2

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

# numpy array indexing(*) 

In [163]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [164]:
#grab 3
a[2]

3

In [162]:
#first 5 elements
a[0:5]

array([1, 2, 3, 4, 5])

In [169]:
#print everything reverse
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [171]:
#slicing an array
slice_array=a[0:6]
slice_array

array([1, 2, 3, 4, 5, 6])

In [175]:
#changing the slice value
slice_array[:]=7
slice_array

array([7, 7, 7, 7, 7, 7])

In [178]:
#when you change the slice value the value of a also changed
a


array([7, 7, 7, 7, 7, 7, 7, 8, 9])

In [179]:
#in-order to overcome this we use copy()
a_copy=a.copy()

## Indexing 2D arrays 

In [181]:
b=np.arange(1,10)
b=b.reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [182]:
#indexing 1 row
b[0]

array([1, 2, 3])

In [183]:
##indexing 2 row
b[1]

array([4, 5, 6])

In [184]:
#grab number 5
b[1][1]

5

In [185]:
#grab number 5
b[1,1]

5

In [188]:
#2D array slicing(grab 5,6,8,9 elements)
b[1:,1:]

array([[5, 6],
       [8, 9]])

In [189]:
#2D array slicing(grab 2,3,5,6 elements)
b[:2,1:]

array([[2, 3],
       [5, 6]])

### Selecting values in array 

In [190]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [191]:
b>4

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [192]:
b[b>4]

array([5, 6, 7, 8, 9])

In [193]:
x=3
b[b>x]

array([4, 5, 6, 7, 8, 9])